spring:
  application:
    name: infuse-api



  datasource:
    url: jdbc:postgresql://localhost:5432/infuse_db
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topic:
      consulta-creditos: consulta-creditos

server:
  servlet:
    context-path: /infuse-api