spring:
  application:
    name: infuse-api

  datasource:
    url: jdbc:postgresql://localhost:5432/infuse_db
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: infuse-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    topic:
      consulta-creditos: consulta-creditos

server:
  servlet:
    context-path: /infuse-api